name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional, skip if no lint script)
        run: npm run lint || echo "Linting skipped"

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build React app
        run: npm run build
