name: Build & Deploy React to Vercel

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/react-front.yml'
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd client && npm i

      - name: Build React app
        run: |
          cd client
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./client
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
